pipeline:
  name: git-checkout
  identifier: gitcheckout
  projectIdentifier: sonarqube
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: ensure
        build: <+input>
  stages:
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: python:latest
                    shell: Bash
                    command: |-
                      pip --version
                      python -m pip install --upgrade pip
                      pip install -r requirements.txt
                      pip install pytest
                      cat /harness/test/test.py
                      pytest /harness/test/test.py --junit-xml=report.xml
                    imagePullPolicy: IfNotPresent
              - step:
                  type: Sonarqube
                  name: Sonarqube_1
                  identifier: Sonarqube_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      workspace: /harness/ensure
                      detection: auto
                    advanced:
                      log:
                        level: info
                    auth:
                      access_token: 5dec96f480ea59a3efda638fc72656a901b153c4
                      domain: https://sonarcloud.io/
                      ssl: true
                    tool:
                      project_key: harness
        delegateSelectors:
          - docker-delegate
        when:
          pipelineStatus: All
