pipeline:
  name: git-checkout
  identifier: gitcheckout
  projectIdentifier: sonarqube
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: ensure
        build: <+input>
  stages:
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: python:latest
                    shell: Bash
                    command: |-
                      pip --version
                      python -m pip install --upgrade pip
                      pip install -r requirements.txt
                      pip install pytest
                      pytest /harness/test/test.py --junit-xml=report.xml
                    imagePullPolicy: IfNotPresent
        delegateSelectors:
          - docker-delegate
        when:
          pipelineStatus: All
